name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # <-- Add this here for the entire workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
    - name: Get tags
      run: git fetch --tags --prune --unshallow
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: autoincrement version
      run: ./autoincrement.sh
    - name: make
      run: make
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: doctest
      run: make test
    - name: run tests
      run: ./test
  
